name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Eigen
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev

      - name: Clean old binaries
        run: |
          rm -f 01.InplaceSorting/sort_demo
          rm -f 01.InplaceSorting/sort_test

      - name: Build and test inplace sorting
        run: |
          cd 01.InplaceSorting
          make clean || true
          make
          ./sort_demo
          ./sort_test

      - name: Build and test Gauss
        run: |
          cd 03.Gauss
          make clean || true
          make
          ./Gauss_test
          ./Gauss_main AB.csv
          ./integration_test.sh
